# Generated by Django 4.1.2 on 2022-10-27 18:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0006_rename_area_legacyarea_and_more'),
        ('users', '0003_alter_profile_area'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='LegacyProfile',
        ),
    ]
