# Generated by Django 4.1.2 on 2022-11-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_utilitymissionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitymissionlog',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
