# Generated by Django 4.1.2 on 2022-11-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_newprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='newprofile',
            name='blacklist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newprofile',
            name='right_to_vote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newprofile',
            name='sex',
            field=models.CharField(default='Female', max_length=20),
            preserve_default=False,
        ),
    ]
