# Generated by Django 4.1.2 on 2022-11-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_newprofile_right_to_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='newprofile',
            name='title',
            field=models.CharField(default='Ms.', max_length=10),
            preserve_default=False,
        ),
    ]
