# Generated by Django 4.1.2 on 2022-11-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_newprofile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newprofile',
            name='sex',
            field=models.CharField(default='Male', max_length=20),
        ),
        migrations.AlterField(
            model_name='newprofile',
            name='title',
            field=models.CharField(default='Mr.', max_length=10),
        ),
    ]
