# Generated by Django 4.1.1 on 2022-09-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(default='default_candidate.png', upload_to='candidates'),
        ),
    ]
