# Generated by Django 4.1.2 on 2022-10-27 18:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_alter_profile_area'),
        ('apps', '0005_party'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Area',
            new_name='LegacyArea',
        ),
        migrations.RenameModel(
            old_name='Candidate',
            new_name='LegacyCandidate',
        ),
        migrations.RenameModel(
            old_name='Election',
            new_name='LegacyElection',
        ),
        migrations.RenameModel(
            old_name='Party',
            new_name='LegacyParty',
        ),
        migrations.RenameModel(
            old_name='Vote',
            new_name='LegacyVote',
        ),
    ]
