# Generated by Django 4.1.1 on 2022-11-02 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_newarea_newcandidate_newelection_voteresultparty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legacyelection',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='newelection',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
