# Generated by Django 4.1.2 on 2022-11-02 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_legacyelection_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteresultparty',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.newparty'),
        ),
    ]
