# Generated by Django 4.1.3 on 2022-11-21 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_newarea_number_of_voters_newarea_population'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newarea',
            name='description',
        ),
    ]
