# Generated by Django 4.1.3 on 2022-11-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_remove_newarea_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newparty',
            name='quote',
            field=models.TextField(default='bruh'),
            preserve_default=False,
        ),
    ]
