# Generated by Django 4.1.3 on 2022-12-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_newparty_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='newarea',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
